name: Moonrepo CI Retrospect
description: Displays the results of `moon ci` in an easy-to-understand format.
inputs:
  skipCached:
    description: 'Skip displaying cached and remote-cached tasks'
    required: false
    default: 'false'
outputs: {}
runs:
  using: node20
  main: dist/index.js
